apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedclaim-api
  namespace: speedclaim
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - __API_HOST__
      secretName: speedclaim-api-tls
  rules:
    - host: __API_HOST__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: speedclaim-api
                port:
                  name: http
