using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace SpeedClaim.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddP3EmailTemplates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "email_templates",
                columns: new[] { "id", "body_html", "created_at", "is_active", "subject", "template_key", "updated_at" },
                values: new object[,]
                {
                    {
                        new Guid("dd000018-0000-0000-0000-000000000018"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Agent Welcome</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">Account Created</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Welcome to SpeedClaim, {{firstName}}!</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Your agent account has been created by an administrator. You can now log in using your registered email address.</p><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border:1px solid #E2E6EB;border-radius:8px;overflow:hidden;\"><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;width:40%;\">Login email</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1A2230;\">{{email}}</td></tr></table><p style=\"margin:20px 0 0;font-size:13px;line-height:1.5;color:#6B7685;\">Please log in and change your password on first sign-in. Contact your administrator if you have any issues accessing your account.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Welcome to SpeedClaim — your agent account is ready",
                        "AgentWelcome",
                        null
                    },
                    {
                        new Guid("dd000019-0000-0000-0000-000000000019"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>KYC Submitted</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E6F4F8;color:#0F6E8C;border-radius:20px;font-size:11px;font-weight:700;\">Under Review</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">KYC document received</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, we have received your KYC document. Our verification team will review it and notify you of the outcome within 2 business days.</p><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">You can check the status of your KYC verification at any time via the customer portal.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "KYC document received — verification in progress",
                        "KycSubmitted",
                        null
                    },
                    {
                        new Guid("dd000020-0000-0000-0000-000000000020"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Proposal Submitted</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E6F4F8;color:#0F6E8C;border-radius:20px;font-size:11px;font-weight:700;\">Submitted</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your proposal has been submitted</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your insurance proposal has been submitted and is awaiting underwriter review.</p><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border:1px solid #E2E6EB;border-radius:8px;overflow:hidden;\"><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;width:40%;\">Proposal number</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1A2230;\">{{proposalNumber}}</td></tr></table><p style=\"margin:20px 0 0;font-size:13px;line-height:1.5;color:#6B7685;\">You will be notified by email once the underwriter has reviewed your proposal. You can also track the status via the customer portal.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Proposal {{proposalNumber}} submitted — under review",
                        "ProposalSubmitted",
                        null
                    },
                    {
                        new Guid("dd000021-0000-0000-0000-000000000021"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Additional Documents Required</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#FBF4E6;color:#B97400;border-radius:20px;font-size:11px;font-weight:700;\">Action Required</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Additional documents needed</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, the underwriter reviewing your proposal <strong>{{proposalNumber}}</strong> requires additional documents before a decision can be made.</p><div style=\"margin:0 0 20px;padding:12px 16px;background:#FBF4E6;border-left:3px solid #B97400;border-radius:4px;\"><p style=\"margin:0 0 4px;font-size:12px;font-weight:700;color:#B97400;\">Details</p><p style=\"margin:0;font-size:14px;color:#3C4654;\">{{details}}</p></div><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">Please log in to the customer portal and upload the requested documents to continue the review.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Action required — additional documents needed for proposal {{proposalNumber}}",
                        "ProposalDocumentsPending",
                        null
                    },
                    {
                        new Guid("dd000022-0000-0000-0000-000000000022"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Premium Payment Confirmed</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">Payment Confirmed</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your premium payment has been received</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, we have received your premium payment. Thank you for keeping your policy active.</p><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border:1px solid #E2E6EB;border-radius:8px;overflow:hidden;\"><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;width:40%;\">Policy number</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1A2230;\">{{policyNumber}}</td></tr><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;\">Instalment</td><td style=\"padding:12px 16px;font-size:14px;color:#1A2230;\">#{{installmentNumber}}</td></tr><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;\">Amount paid</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1F9D6B;\">{{amount}}</td></tr></table><p style=\"margin:20px 0 0;font-size:13px;line-height:1.5;color:#6B7685;\">You can download your payment receipt from the customer portal at any time.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Premium payment confirmed for policy {{policyNumber}}",
                        "PremiumPaymentConfirmed",
                        null
                    },
                    {
                        new Guid("dd000023-0000-0000-0000-000000000023"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Endorsement Requested</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E6F4F8;color:#0F6E8C;border-radius:20px;font-size:11px;font-weight:700;\">Request Received</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Endorsement request submitted</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your endorsement request has been received and forwarded to the underwriter for review.</p><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border:1px solid #E2E6EB;border-radius:8px;overflow:hidden;\"><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;width:40%;\">Policy number</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1A2230;\">{{policyNumber}}</td></tr><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;\">Change type</td><td style=\"padding:12px 16px;font-size:14px;color:#1A2230;\">{{endorsementType}}</td></tr></table><p style=\"margin:20px 0 0;font-size:13px;line-height:1.5;color:#6B7685;\">You will be notified by email once the underwriter has made a decision on your request.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Endorsement request received for policy {{policyNumber}}",
                        "EndorsementRequested",
                        null
                    },
                    {
                        new Guid("dd000024-0000-0000-0000-000000000024"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Claim Documents Required</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#FBF4E6;color:#B97400;border-radius:20px;font-size:11px;font-weight:700;\">Action Required</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Documents required for your claim</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, the claims officer reviewing your claim <strong>{{claimNumber}}</strong> requires additional supporting documents before the review can proceed.</p><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">Please log in to the customer portal and upload the requested documents at your earliest convenience.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Action required — documents needed for claim {{claimNumber}}",
                        "ClaimDocumentsPending",
                        null
                    },
                    {
                        new Guid("dd000025-0000-0000-0000-000000000025"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Claim Under Review</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E6F4F8;color:#0F6E8C;border-radius:20px;font-size:11px;font-weight:700;\">Under Review</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your claim is being reviewed</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your claim <strong>{{claimNumber}}</strong> is now under active review by our claims team. We will notify you as soon as a decision has been reached.</p><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">You can track the real-time status of your claim via the customer portal.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Claim {{claimNumber}} is now under review",
                        "ClaimUnderReview",
                        null
                    },
                    {
                        new Guid("dd000026-0000-0000-0000-000000000026"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Pre-Authorization Requested</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E6F4F8;color:#0F6E8C;border-radius:20px;font-size:11px;font-weight:700;\">Pre-Auth Requested</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Pre-authorization has been requested</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, a pre-authorization request has been raised for your claim <strong>{{claimNumber}}</strong>. Our team will process this and notify you of the outcome.</p><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">Pre-authorizations are typically reviewed within 24 hours. You can track the status via the customer portal.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Pre-authorization requested for claim {{claimNumber}}",
                        "ClaimPreAuthRequested",
                        null
                    },
                    {
                        new Guid("dd000027-0000-0000-0000-000000000027"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Pre-Authorization Approved</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">Pre-Auth Approved</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Pre-authorization approved</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, the pre-authorization for your claim <strong>{{claimNumber}}</strong> has been approved. Your claim will now proceed to the final review stage.</p><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">You will be notified once the final claim decision has been made. Track the status via the customer portal.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Pre-authorization approved for claim {{claimNumber}}",
                        "ClaimPreAuthApproved",
                        null
                    },
                    {
                        new Guid("dd000028-0000-0000-0000-000000000028"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Policy Issued</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">Policy Issued</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your policy has been issued</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your insurance policy has been issued following the approval of your proposal. Please make your first premium payment to activate your coverage.</p><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border:1px solid #E2E6EB;border-radius:8px;overflow:hidden;\"><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;width:40%;\">Policy number</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1A2230;\">{{policyNumber}}</td></tr><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;\">Proposal number</td><td style=\"padding:12px 16px;font-size:14px;color:#1A2230;\">{{proposalNumber}}</td></tr></table><p style=\"margin:20px 0 0;font-size:13px;line-height:1.5;color:#6B7685;\">Log in to the customer portal to make your first premium payment and activate your policy.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Policy {{policyNumber}} issued — pay your first premium to activate",
                        "PolicyIssued",
                        null
                    },
                    {
                        new Guid("dd000029-0000-0000-0000-000000000029"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Grievance Escalated</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#FBF4E6;color:#B97400;border-radius:20px;font-size:11px;font-weight:700;\">Escalated</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your grievance has been escalated</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your grievance <strong>{{grievanceNumber}}</strong> has been escalated to our senior resolution team for further review. We take this matter seriously and will work to resolve it as quickly as possible.</p><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">You will be contacted once a resolution has been reached. Track the status via the customer portal.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Your grievance {{grievanceNumber}} has been escalated",
                        "GrievanceEscalated",
                        null
                    },
                    {
                        new Guid("dd000030-0000-0000-0000-000000000030"),
                        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Commission Credited</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">Commission Paid</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your commission has been credited</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your commission for a policy has been approved and credited to your account.</p><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border:1px solid #E2E6EB;border-radius:8px;overflow:hidden;\"><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;width:40%;\">Policy number</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1A2230;\">{{policyNumber}}</td></tr><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;\">Commission amount</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1F9D6B;\">{{commissionAmount}}</td></tr></table><p style=\"margin:20px 0 0;font-size:13px;line-height:1.5;color:#6B7685;\">You can view all your commissions via the agent portal.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>",
                        new DateTimeOffset(new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                        true,
                        "Commission of {{commissionAmount}} credited for policy {{policyNumber}}",
                        "CommissionCredited",
                        null
                    }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000018-0000-0000-0000-000000000018"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000019-0000-0000-0000-000000000019"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000020-0000-0000-0000-000000000020"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000021-0000-0000-0000-000000000021"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000022-0000-0000-0000-000000000022"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000023-0000-0000-0000-000000000023"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000024-0000-0000-0000-000000000024"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000025-0000-0000-0000-000000000025"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000026-0000-0000-0000-000000000026"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000027-0000-0000-0000-000000000027"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000028-0000-0000-0000-000000000028"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000029-0000-0000-0000-000000000029"));
            migrationBuilder.DeleteData(table: "email_templates", keyColumn: "id", keyValue: new Guid("dd000030-0000-0000-0000-000000000030"));
        }
    }
}
