using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace SpeedClaim.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddP2AEmailTemplates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "email_templates",
                columns: new[] { "id", "body_html", "created_at", "is_active", "subject", "template_key", "updated_at" },
                values: new object[,]
                {
                    { new Guid("dd000012-0000-0000-0000-000000000012"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Claim Filed</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E6F4F8;color:#0F6E8C;border-radius:20px;font-size:11px;font-weight:700;\">Claim Received</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your claim has been filed</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your claim has been successfully filed and assigned to our team for review.</p><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border:1px solid #E2E6EB;border-radius:8px;overflow:hidden;\"><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;width:40%;\">Claim number</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1A2230;\">{{claimNumber}}</td></tr><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;\">Policy number</td><td style=\"padding:12px 16px;font-size:14px;color:#1A2230;\">{{policyNumber}}</td></tr></table><p style=\"margin:20px 0 0;font-size:13px;line-height:1.5;color:#6B7685;\">You will be notified as the status of your claim is updated. You can track your claim in real time via the customer portal.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Claim {{claimNumber}} filed — we have received your request", "ClaimIntimated", null },
                    { new Guid("dd000013-0000-0000-0000-000000000013"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Endorsement Approved</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">Endorsement Approved</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your policy change has been approved</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your endorsement request of type <strong>{{endorsementType}}</strong> for policy <strong>{{policyNumber}}</strong> has been approved and applied.</p><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">The changes are now effective on your policy. Please log in to review the updated policy details.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Endorsement approved for policy {{policyNumber}}", "EndorsementApproved", null },
                    { new Guid("dd000014-0000-0000-0000-000000000014"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Endorsement Rejected</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#FBE9E9;color:#D14343;border-radius:20px;font-size:11px;font-weight:700;\">Endorsement Rejected</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your policy change could not be approved</h1><p style=\"margin:0 0 16px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your endorsement request of type <strong>{{endorsementType}}</strong> for policy <strong>{{policyNumber}}</strong> has not been approved.</p><div style=\"margin:0 0 20px;padding:12px 16px;background:#FBE9E9;border-left:3px solid #D14343;border-radius:4px;\"><p style=\"margin:0 0 4px;font-size:12px;font-weight:700;color:#D14343;\">Reason</p><p style=\"margin:0;font-size:14px;color:#3C4654;\">{{rejectionReason}}</p></div><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">Please contact your agent or our support team for further assistance.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Endorsement request for policy {{policyNumber}} could not be approved", "EndorsementRejected", null },
                    { new Guid("dd000015-0000-0000-0000-000000000015"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Grievance Filed</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E6F4F8;color:#0F6E8C;border-radius:20px;font-size:11px;font-weight:700;\">Grievance Received</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your grievance has been registered</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, we have received your grievance and assigned it reference number <strong>{{grievanceNumber}}</strong>. Our team will review it and get back to you within 7 business days.</p><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">You can track the status of your grievance at any time via the customer portal.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Grievance {{grievanceNumber}} received — we will get back to you", "GrievanceFiled", null },
                    { new Guid("dd000016-0000-0000-0000-000000000016"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Grievance Resolved</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">Grievance Resolved</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your grievance has been resolved</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your grievance <strong>{{grievanceNumber}}</strong> has been reviewed and resolved by our team.</p><div style=\"margin:0 0 20px;padding:12px 16px;background:#F7F9FA;border-left:3px solid #0F6E8C;border-radius:4px;\"><p style=\"margin:0 0 4px;font-size:12px;font-weight:700;color:#0F6E8C;\">Resolution</p><p style=\"margin:0;font-size:14px;color:#3C4654;\">{{resolutionNotes}}</p></div><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">If you are not satisfied with the resolution, you may escalate via the customer portal.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Your grievance {{grievanceNumber}} has been resolved", "GrievanceResolved", null },
                    { new Guid("dd000017-0000-0000-0000-000000000017"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Premium Overdue</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#FBE9E9;color:#D14343;border-radius:20px;font-size:11px;font-weight:700;\">Premium Overdue</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your premium payment is overdue</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, a premium payment for your policy is now overdue. Please make your payment as soon as possible to avoid a lapse in coverage.</p><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border:1px solid #E2E6EB;border-radius:8px;overflow:hidden;\"><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;width:40%;\">Policy number</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1A2230;\">{{policyNumber}}</td></tr><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;\">Amount due</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#D14343;\">{{amount}} INR</td></tr><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;\">Was due on</td><td style=\"padding:12px 16px;font-size:14px;color:#1A2230;\">{{dueDate}}</td></tr></table><p style=\"margin:20px 0 0;font-size:13px;line-height:1.5;color:#6B7685;\">Log in to the customer portal to make your payment immediately.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Action required — premium overdue for policy {{policyNumber}}", "PremiumOverdue", null }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000012-0000-0000-0000-000000000012"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000013-0000-0000-0000-000000000013"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000014-0000-0000-0000-000000000014"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000015-0000-0000-0000-000000000015"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000016-0000-0000-0000-000000000016"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000017-0000-0000-0000-000000000017"));
        }
    }
}
