using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace SpeedClaim.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddP1EmailNotificationTemplates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "email_templates",
                columns: new[] { "id", "body_html", "created_at", "is_active", "subject", "template_key", "updated_at" },
                values: new object[,]
                {
                    { new Guid("dd000004-0000-0000-0000-000000000004"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>KYC Verified</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">KYC Verified</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your identity has been verified</h1><p style=\"margin:0;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your KYC documents have been successfully reviewed and verified. You are now eligible to apply for insurance products and have policies issued.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Your KYC has been verified - SpeedClaim", "KycApproved", null },
                    { new Guid("dd000005-0000-0000-0000-000000000005"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>KYC Rejected</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#FBE9E9;color:#D14343;border-radius:20px;font-size:11px;font-weight:700;\">KYC Rejected</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">KYC verification unsuccessful</h1><p style=\"margin:0 0 16px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, we were unable to verify your identity documents.</p><div style=\"margin:0 0 20px;padding:12px 16px;background:#FBE9E9;border-left:3px solid #D14343;border-radius:4px;\"><p style=\"margin:0 0 4px;font-size:12px;font-weight:700;color:#D14343;\">Reason</p><p style=\"margin:0;font-size:14px;color:#3C4654;\">{{rejectionReason}}</p></div><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">Please log in to the customer portal to re-upload your documents.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "KYC verification unsuccessful - SpeedClaim", "KycRejected", null },
                    { new Guid("dd000006-0000-0000-0000-000000000006"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Proposal Approved</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">Proposal Approved</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your proposal has been approved</h1><p style=\"margin:0;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your insurance proposal <strong>{{proposalNumber}}</strong> has been reviewed and approved by our underwriting team. A policy has been created and will activate once your first premium payment is received. Please log in to complete your payment.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Your proposal {{proposalNumber}} has been approved", "ProposalApproved", null },
                    { new Guid("dd000007-0000-0000-0000-000000000007"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Proposal Rejected</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#FEF6E6;color:#D9920A;border-radius:20px;font-size:11px;font-weight:700;\">Proposal Rejected</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your proposal could not be approved</h1><p style=\"margin:0 0 16px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, after careful review, your proposal <strong>{{proposalNumber}}</strong> has not been approved.</p><div style=\"margin:0 0 20px;padding:12px 16px;background:#FEF6E6;border-left:3px solid #D9920A;border-radius:4px;\"><p style=\"margin:0 0 4px;font-size:12px;font-weight:700;color:#D9920A;\">Reason</p><p style=\"margin:0;font-size:14px;color:#3C4654;\">{{rejectionReason}}</p></div><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">You may contact your assigned agent or our support team for more information.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Your proposal {{proposalNumber}} could not be approved", "ProposalRejected", null },
                    { new Guid("dd000008-0000-0000-0000-000000000008"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Claim Approved</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">Claim Approved</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your claim has been approved</h1><p style=\"margin:0;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your claim <strong>{{claimNumber}}</strong> has been approved following our investigation. Your payout will be processed shortly. You will receive a separate notification once the payment has been disbursed.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Your claim {{claimNumber}} has been approved", "ClaimApproved", null },
                    { new Guid("dd000009-0000-0000-0000-000000000009"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Claim Rejected</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#FBE9E9;color:#D14343;border-radius:20px;font-size:11px;font-weight:700;\">Claim Rejected</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your claim could not be approved</h1><p style=\"margin:0 0 16px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, after investigation, your claim <strong>{{claimNumber}}</strong> has not been approved.</p><div style=\"margin:0 0 20px;padding:12px 16px;background:#FBE9E9;border-left:3px solid #D14343;border-radius:4px;\"><p style=\"margin:0 0 4px;font-size:12px;font-weight:700;color:#D14343;\">Reason</p><p style=\"margin:0;font-size:14px;color:#3C4654;\">{{rejectionReason}}</p></div><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">You may contact us to appeal this decision or submit additional evidence.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Your claim {{claimNumber}} could not be approved", "ClaimRejected", null },
                    { new Guid("dd000010-0000-0000-0000-000000000010"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Claim Settled</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#E8F7F1;color:#1F9D6B;border-radius:20px;font-size:11px;font-weight:700;\">Claim Settled</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your claim payout has been processed</h1><p style=\"margin:0 0 20px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your claim <strong>{{claimNumber}}</strong> has been financially settled.</p><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border:1px solid #E2E6EB;border-radius:8px;overflow:hidden;\"><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;width:40%;\">Claim number</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1A2230;\">{{claimNumber}}</td></tr><tr><td style=\"padding:12px 16px;background:#F7F9FA;font-size:12px;color:#6B7685;\">Payout amount</td><td style=\"padding:12px 16px;font-size:14px;font-weight:700;color:#1F9D6B;\">{{payoutAmount}} INR</td></tr></table></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Your claim {{claimNumber}} has been settled", "ClaimSettled", null },
                    { new Guid("dd000011-0000-0000-0000-000000000011"), "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Policy Cancelled</title></head><body style=\"margin:0;padding:0;background-color:#F7F9FA;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;\"><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#F7F9FA;padding:32px 16px;\"><tr><td align=\"center\"><table role=\"presentation\" width=\"480\" cellpadding=\"0\" cellspacing=\"0\" style=\"max-width:480px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;\"><tr><td style=\"background:linear-gradient(160deg,#0F6E8C 0%,#0A3040 100%);padding:28px 32px;text-align:center;\"><span style=\"font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;\">SpeedClaim</span></td></tr><tr><td style=\"padding:32px;\"><span style=\"display:inline-block;margin:0 0 12px;padding:4px 10px;background:#FEF6E6;color:#D9920A;border-radius:20px;font-size:11px;font-weight:700;\">Policy Cancelled</span><h1 style=\"margin:0 0 16px;font-size:22px;font-weight:600;color:#1A2230;\">Your policy has been cancelled</h1><p style=\"margin:0 0 16px;font-size:15px;line-height:1.6;color:#3C4654;\">Dear {{firstName}}, your policy <strong>{{policyNumber}}</strong> has been cancelled as requested.</p><p style=\"margin:0;font-size:13px;line-height:1.5;color:#6B7685;\">If you did not request this cancellation, please contact SpeedClaim support immediately.</p></td></tr><tr><td style=\"padding:20px 32px;border-top:1px solid #E2E6EB;text-align:center;\"><p style=\"margin:0;font-size:12px;color:#6B7685;\">&copy; {{year}} SpeedClaim. All rights reserved.</p></td></tr></table></td></tr></table></body></html>", new DateTimeOffset(new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), true, "Your policy {{policyNumber}} has been cancelled", "PolicyCancelled", null }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000004-0000-0000-0000-000000000004"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000005-0000-0000-0000-000000000005"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000006-0000-0000-0000-000000000006"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000007-0000-0000-0000-000000000007"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000008-0000-0000-0000-000000000008"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000009-0000-0000-0000-000000000009"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000010-0000-0000-0000-000000000010"));

            migrationBuilder.DeleteData(
                table: "email_templates",
                keyColumn: "id",
                keyValue: new Guid("dd000011-0000-0000-0000-000000000011"));
        }
    }
}
