import { Component, Input, OnChanges, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { PolicyAssistantAvailabilityDto, PolicyAssistantConversationDto, PolicyAssistantMessageDto } from '../../../../core/models/api.models';
import { PolicyService } from '../services/policy.service';

@Component({ selector: 'app-policy-guide', standalone: true, imports: [FormsModule], templateUrl: './policy-guide.html' })
export class PolicyGuideComponent implements OnChanges {
  @Input({ required: true }) policyId = ''; @Input() domain = '';
  private readonly policies = inject(PolicyService);
  availability = signal<PolicyAssistantAvailabilityDto | null>(null); conversations = signal<PolicyAssistantConversationDto[]>([]); active = signal<PolicyAssistantConversationDto | null>(null); sending = signal(false); question = signal(''); error = signal<string | null>(null); selectedCitation = signal<number | null>(null);
  readonly suggestions = ['What is the waiting period?', 'What is not covered by this policy?', 'Can I change my nominee?', 'What documents does the brochure mention for a claim?'];
  ngOnChanges(): void { if (!this.policyId) return; this.policies.getAssistantAvailability(this.policyId).subscribe({ next: x => { this.availability.set(x); if (x.available) this.loadHistory(); }, error: () => this.error.set('Policy Guide is temporarily unavailable. Please try again later.') }); }
  loadHistory(): void { this.policies.getAssistantConversations(this.policyId).subscribe({ next: list => { this.conversations.set(list); if (list[0]) this.open(list[0]); }, error: () => this.error.set('Conversation history could not be loaded.') }); }
  open(conversation: PolicyAssistantConversationDto): void { this.policies.getAssistantConversation(this.policyId, conversation.id).subscribe({ next: x => this.active.set(x), error: () => this.error.set('That conversation is unavailable.') }); }
  newConversation(): void { this.policies.createAssistantConversation(this.policyId).subscribe({ next: x => { this.conversations.update(list => [x, ...list]); this.active.set({ ...x, messages: [] }); }, error: err => this.error.set(err?.error?.message ?? 'Could not start a new conversation.') }); }
  ask(value?: string): void { const question = (value ?? this.question()).trim(); if (!question || this.sending()) return; this.error.set(null); this.question.set(question); const send = (conversation: PolicyAssistantConversationDto) => { this.sending.set(true); this.policies.sendAssistantMessage(this.policyId, conversation.id, question).subscribe({ next: answer => { const messages: PolicyAssistantMessageDto[] = [...(this.active()?.messages ?? []), { id: 'pending-user', role: 'User', content: question, citations: [], createdAt: new Date().toISOString() }, { id: answer.messageId, role: 'Assistant', content: answer.answer, evidenceStatus: answer.evidenceStatus, citations: answer.citations, createdAt: new Date().toISOString() }]; this.active.set({ ...conversation, brochureVersion: answer.brochureVersion, messages }); this.question.set(''); this.sending.set(false); }, error: err => { this.sending.set(false); this.error.set(err?.status === 429 ? 'Policy Guide is busy. Please wait a moment and retry.' : err?.error?.message ?? 'Policy Guide is temporarily unavailable.'); } }); }; const current = this.active(); if (current) send(current); else this.policies.createAssistantConversation(this.policyId).subscribe({ next: x => { this.conversations.update(list => [x, ...list]); this.active.set({ ...x, messages: [] }); send(x); }, error: () => this.error.set('Could not start a conversation.') }); }
  selectCitation(index: number): void { this.selectedCitation.set(index); document.getElementById(`policy-guide-source-${index}`)?.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }
}
